### ISSUE TITLE
Tutorial ambiguity

### ISSUE THREAD

**Issue by kellermac** [daler/metaseq#12]
I am relatively new to python and am having trouble following the tutorial provided. In bash I load the (metaseq-test) environment, downloaded the example data to ~/metaseq-example/data. At this point the tutorial confueses me. I can set the variable data_dir = 'metaseq-example/data' if I switch to python, but then commands like "ls" and "head" don't work. If you switch to bash, it doesn't know the python variables, and you cannot set them in bash like you show in the tutorial. 

Sorry to complain about what I am sure is an elementary issue, but I feel the tutorial could be a bit more clear in this regard. Thank you! -Keller

**Comment by kellermac** [comment]
It is in bash. The tutorial should read [ data_dir='metaseq-example/data' ]. i.e. omit the spaces. Like I said an elementary issue, but it trips up young greenears like me. -Keller

**Comment by kellermac** [comment]
The beginning is in bash. The tutorial should read [ data_dir='metaseq-example/data' ]. i.e. omit the spaces. Then it looks as if you switch over to python when we [ import os ]. Am I missing something? Would you please provide a bit of an explanation on the swapping of shells, and how it should be managed? Thank You!

**Comment by kellermac** [comment]
Also what is with the ! in front of some bash commands !ls !head !cat. My understanding in this context is that !{string} will search your bash history for a line beginning with that string and print the line. I have been omiting it.

**Comment by daler** [comment]
That's IPython notebook syntax (and IPython interpreter syntax as well), where you use the "`!`" for one-line system calls. Otherwise, Python is expected.  I've updated the docs in the source to clarify this, but the PyPI docs server is down so I can't upload the new version.
