### ISSUE TITLE
hg19 Random Chromosome Issues

### ISSUE THREAD

**Issue by jlpulice** [daler/metaseq#13]
Hi,

I'm wondering if there's a way to deal with the random chromosomes that hg19 includes not in their chromosome, ie. "chr9_gl000199_random" and "chr6_cox_hap2". I'm having issues in that metaseq can't handle those reads when they are in the TSS data set or in the peaks data set I am trying to use, and returns error messages until I remove them. Is there a better option that simply removing this data from my ranges that metaseq is handling, as they are obligatory members of the hg19 build?

Thanks!
John

**Comment by daler** [comment]
This will happen with BAM files in general, independently of metaseq -- if you ask for reads from a BAM file coming from a chromosome that doesn't exist in its index, you'll get an error.

You'll have to decide whether you want to re-map your reads to the full assembly that contains those chromosomes, or remove the features with those chromosomes from you TSSs or peaks.

Have a look at `pybedtools.BedTool.filter()` for the latter, e.g, 

```python
tsses = pybedtools.BedTool('TSS.bed')\
   .filter(lambda f: '_' not in f.chrom)\
   .saveas('TSS_filtered.bed')
```
