### ISSUE TITLE
metaseq is supported by python 3?

### ISSUE THREAD

**Issue by BioNinja** [daler/metaseq#15]
Hi daler,  I love your metaseq, and pybedtools. Have you considered to upgrade metaseq, so we could do better data analysis work on python 3?

**Comment by daler** [comment]
Certainly! Getting pybedtools over to Py3 was a big step, metaseq is next.

**Comment by BioNinja** [comment]
Thanks for your great job. I'm looking forward to the new metaseq. 

By the way, I had a question  when I use metaseq to analysis my own chip-seq data. 
In order to  create “genomic signal” objects out of the data, we could use **metaseq.genomic_signal** method. However, if I specify the kind='bigWig', which was generated by MACS, do I need to normalize to library size like you did for 'bam'?

**Comment by daler** [comment]
A bigWig is just values; whether or not they are normalized depends on the program that generated them. If you're using MACS 2, you might want to use the `--SPMR` flag.

**Comment by BioNinja** [comment]
Thanks again for your help. I'm much clear now.

**Comment by imk1** [comment]
Is metaseq now supported by python 3, or is it still only supported by python 2?  Thanks!

**Comment by daler** [comment]
@imk1 nowadays I would recommend using deepTools, which has much of the same functionality and works in py3. I've had no time to work on metaseq for a while!

**Comment by imk1** [comment]
Thanks!  I was thinking of trying that out too.
