### ISSUE TITLE
Can the browser be used to programmatically create graphs for genes of interest?

### ISSUE THREAD

**Issue by endrebak** [daler/metaseq#21]
Let us say I have a PolII experiment where I want to do a sanity check by seeing the TSS of certain genes. Is this possible to do programatically in metaseq? Feed it the name/regions of 20 genes and have it automatically create graphs? Would be a neat example to have in the docs.

**Comment by daler** [comment]
Sure. Here's an example from the supplemental figs of the paper:
 
![selection_016](https://cloud.githubusercontent.com/assets/115406/12984896/f9ed6d62-d0bd-11e5-9089-e1cd5a4d9e42.png)

It's showing library-size normalized RIP-seq IP and input from BAMs over a gene of interest, with gene models at the bottom.

You just have to decide what you want to show and how to show it; the tools are there: feed the 20 genes to `genomic_signal.array()` and plot the 20 rows of the resulting numpy.array in any way you'd like using seaborn/matplotlib/bokeh etc.

**Comment by endrebak** [comment]
Good stuff. I'll get more free time to play around with this in a month or so, seems like it'll be really useful.
