### ISSUE TITLE
A problem when running the script

### ISSUE THREAD

**Issue by i19870503** [daler/metaseq#22]
Hi daler, I recently used metaseq to draw tss-plot, but I am stuck in the function of 'ip_signal.array() and input_signal.array ()'. When I run the script it comes up with the error below. I use canopy and python version is 2.7.9, would help me with than problem? thanks

> TypeError                                 Traceback (most recent call last)
<ipython-input-11-30b389f4f623> in <module>()
     14 
     15         # Use multiple CPUs. Dramatically speeds up run time.
---> 16         processes=processes)
     17 
     18     # Do the same thing for input.

>/home/zluna/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/metaseq-0.5.5.4-py2.7.egg/metaseq/_genomic_signal.pyc in array(self, features, processes, chunksize, ragged, **kwargs)
    120             arrays = _array_parallel(
    121                 self.fn, self.__class__, features, processes=processes,
--> 122                 chunksize=chunksize, **kwargs)
    123         else:
    124             arrays = _array(self.fn, self.__class__, features, **kwargs)

>/home/zluna/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/metaseq-0.5.5.4-py2.7.egg/metaseq/array_helpers.pyc in _array_parallel(fn, cls, genelist, chunksize, processes, **kwargs)
    381             itertools.repeat(cls),
    382             chunks,
--> 383             itertools.repeat(kwargs)))
    384     pool.close()
    385     pool.join()

>/home/zluna/Canopy/appdata/canopy-1.5.5.3123.rh5-x86_64/lib/python2.7/multiprocessing/pool.pyc in map(self, func, iterable, chunksize)
    249         '''
    250         assert self._state == RUN
--> 251         return self.map_async(func, iterable, chunksize).get()
    252 
    253     def imap(self, func, iterable, chunksize=1):

>/home/zluna/Canopy/appdata/canopy-1.5.5.3123.rh5-x86_64/lib/python2.7/multiprocessing/pool.pyc in get(self, timeout)
    556             return self._value
    557         else:
--> 558             raise self._value
    559 
    560     def _set(self, i, obj):

>TypeError: Expected bytes, got unicode

**Comment by daler** [comment]
Can you provide the versions of metaseq, pybedtools, and pysam you currently have installed? Then please try using `processes=None` instead of `processes=processes` (line 16 in the traceback above), which will help me debug.

Alternatively, you can get the updated versions of everything using [bioconda](https://bioconda.github.io/). The example should work then because this is what's used to build the documentation itself:

```bash
conda install -c bioconda metaseq
```

**Comment by i19870503** [comment]
I tried `processes=None ` but also have the "TypeError: Expected bytes, got unicode ".

> Metadata-Version: 1.1
Name: metaseq
Version: 0.5.5.4
Summary: Integrative analysis of high-thoughput sequencing data
Home-page: http://github.com/daler/metaseq
Author: Ryan Dale
Author-email: dalerr@niddk.nih.gov
License: MIT
Location: /home/zluna/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/metaseq-0.5.5.4-py2.7.egg
Requires: scipy, biopython, scikit-learn, bx-python, Cython, numpy, matplotlib, pandas, openpyxl, pysam, gffutils, PyYAML, pybedtools, nose, pycurl, urlgrabber

> Metadata-Version: 1.1
Name: pybedtools
Version: 0.7.6
Summary: Wrapper around BEDTools for bioinformatics work
Home-page: https://github.com/daler/pybedtools
Author: Ryan Dale
Author-email: dalerr@niddk.nih.gov
License: GPLv2
Location: /home/zluna/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pybedtools-0.7.6-py2.7-linux-x86_64.egg
Requires: six

> Metadata-Version: 1.1
Name: pysam
Version: 0.8.3
Summary: pysam
Home-page: https://github.com/pysam-developers/pysam
Author: Andreas Heger
Author-email: andreas.heger@gmail.com
License: MIT
Location: /home/zluna/Enthought/Canopy_64bit/User/lib/python2.7/site-packages
Requires: 

Do you think the set of canopy have problem? In my opinion the python of canopy using the usc2 not the usc4.

**Comment by daler** [comment]
Could you paste the full error message after running with `processes=None`?

**Comment by i19870503** [comment]
Sure. I recompiled python 2.7.11 and used jupyter to run the script, finally it works. So I duobt the maxunicode cause the error, maybe import some packages which based on ucs2 can not work well the metaseq. The error info with `processes=None` list below:

>TypeError                                 Traceback (most recent call last)
<ipython-input-7-bcb6c8323b6b> in <module>()
     14 
     15         # Use multiple CPUs. Dramatically speeds up run time.
---> 16         processes=None)
     17 
     18     # Do the same thing for input.

>/home/zluna/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/metaseq-0.5.5.4-py2.7.egg/metaseq/_genomic_signal.pyc in array(self, features, processes, chunksize, ragged, **kwargs)
    122                 chunksize=chunksize, **kwargs)
    123         else:
--> 124             arrays = _array(self.fn, self.__class__, features, **kwargs)
    125         if not ragged:
    126             stacked_arrays = np.row_stack(arrays)

>/home/zluna/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/metaseq-0.5.5.4-py2.7.egg/metaseq/array_helpers.pyc in _array(fn, cls, genelist, **kwargs)
    413             gene = [gene]
    414         coverage_x, coverage_y = _local_coverage_func(
--> 415             reader, gene, **kwargs)
    416         biglist.append(coverage_y)
    417     return biglist

>/home/zluna/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/metaseq-0.5.5.4-py2.7.egg/metaseq/_genomic_signal.pyc in local_coverage(self, features, *args, **kwargs)
    133         processes = kwargs.pop('processes', None)
    134         if not processes:
--> 135             return _local_coverage(self.adapter, features, *args, **kwargs)
    136 
    137         if isinstance(features, (list, tuple)):

>/home/zluna/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/metaseq-0.5.5.4-py2.7.egg/metaseq/array_helpers.pyc in _local_coverage(reader, features, read_strand, fragment_size, shift_width, bins, use_score, accumulate, preserve_total, method, processes, stranded, verbose)
    262             profile = np.zeros(window_size, dtype=float)
    263 
--> 264             for interval in reader[padded_window]:
    265 
    266                 if read_strand:

>/home/zluna/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/metaseq-0.5.5.4-py2.7.egg/metaseq/filetype_adapters.pyc in __getitem__(self, key)
     55             key.chrom,
     56             key.start,
---> 57             key.stop)
     58         for r in iterator:
     59             start = r.pos

>/home/zluna/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pysam/calignmentfile.so in pysam.calignmentfile.AlignmentFile.fetch (pysam/calignmentfile.c:9892)()

>/home/zluna/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pysam/calignmentfile.so in pysam.calignmentfile.AlignmentFile._parseRegion (pysam/calignmentfile.c:8831)()

>/home/zluna/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pysam/calignmentfile.so in pysam.calignmentfile.AlignmentFile.gettid (pysam/calignmentfile.c:7841)()

>/home/zluna/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pysam/calignmentfile.so in pysam.calignmentfile._forceBytes (pysam/calignmentfile.c:3659)()

>TypeError: Expected bytes, got unicode
