### ISSUE TITLE
IndexError AND Value error

### ISSUE THREAD

**Issue by kellermac** [daler/metaseq#23]
Hi again. I was hoping you might help me guess the source of some errors I have been getting. I am trying to make average plots of bigwig histone mark data (~25 files), plotted around my TFBS (gff file).  I made a python script with all the files included, which I can prune down later. Trying to execute the file gave me this error: 
 (metaseq-test)hart@hart-ubuntu:~/BigData/gff$ python bf.py
Traceback (most recent call last):
  File "bf.py", line 181, in <module>
    arrays['H2Av'].mean(axis=0),
  File "/home/hart/miniconda/envs/metaseq-test/lib/python2.7/site-packages/numpy/core/_methods.py", line 56, in _mean
    rcount = _count_reduce_items(arr, axis)
  File "/home/hart/miniconda/envs/metaseq-test/lib/python2.7/site-packages/numpy/core/_methods.py", line 50, in _count_reduce_items
    items *= arr.shape[ax]
IndexError: tuple index out of range

After failing to understand the cause of the error. I Just commented out the offending section of code. This allowed the program to finish. However the average plot generated had no signal on it, so I decided to replace the TFBS.gff3 with an older one that I have previously used to make these plots.
Now when running the script I get a new error message: 
 (metaseq-test)hart@hart-ubuntu:~/BigData/gff$ python bf.py
Traceback (most recent call last):
  File "bf.py", line 54, in <module>
    processes=4)
  File "/home/hart/miniconda/envs/metaseq-test/lib/python2.7/site-packages/metaseq/_genomic_signal.py", line 126, in array
    stacked_arrays = np.row_stack(arrays)
  File "/home/hart/miniconda/envs/metaseq-test/lib/python2.7/site-packages/numpy/core/shape_base.py", line 230, in vstack
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
ValueError: need at least one array to concatenate

So any guesses as to what is causing the errors? Thank you!

**Comment by daler** [comment]
I would recommend using IPython, and when you get the error, run the debugger. Then interactively inspect `arrays['H2Av']` to see if it is in fact what you think it is.

Other than that, I'd need to see a minimal example that reproduces the issue. It all depends on what the other parts of `bf.py` are doing.

**Comment by imk1** [comment]
I am getting the same error.  I run bam = metaseq.genomic_signal(bam_file, 'bam') on a bam file that I know is not empty.  I then run bam.array(bedtoolName, bins=400).  Did you ever figure out how to solve this problem?  Thanks!

**Comment by imk1** [comment]
Reverting to numpy version 1.13.3 seems to have solved the problem.
