### ISSUE TITLE
Issue with Example 1 

### ISSUE THREAD

**Issue by pavo** [daler/metaseq#24]
I am working through the iPython Notebook and am getting an error related to pybedtools.  I checked and tsses.gtf is indeed generated from the previous step.  

`tsses_1kb = tsses.slop(b=1000, genome='hg19', output='tsses-1kb.gtf')`

```
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-32-7282d1e13f96> in <module>()
----> 1 tsses_1kb = tsses.slop(b=1000, genome='hg19', output='tsses-1kb.gtf')

/usr/local/lib/python2.7/dist-packages/pybedtools/bedtool.pyc in decorated(self, *args, **kwargs)
    771             # this calls the actual method in the first place; *result* is
    772             # whatever you get back
--> 773             result = method(self, *args, **kwargs)
    774 
    775             # add appropriate tags

/usr/local/lib/python2.7/dist-packages/pybedtools/bedtool.pyc in not_implemented_func(*args, **kwargs)
    201         if not_implemented:
    202             def not_implemented_func(*args, **kwargs):
--> 203                 raise NotImplementedError(help_str)
    204             return not_implemented_func
    205 

NotImplementedError: "slopBed" does not appear to be installed or on the path, so this method is disabled.  Please install a more recent version of BEDTools and re-import to use this method.
```

I tried to `pip install --update pybedtools` but I already have the latest version installed.  Also installed bedtools 2.17.0-1 but I think the above error is asking me to update pybedtools (?).

**Comment by pavo** [comment]
I think that installing pybedtools itself may have fixed this issue, because example1 now works.  I installed metaseq using pip.  should pybedtools be included in the package?  thanks!

**Comment by daler** [comment]
The error you're getting is that `slopBed` from `BEDTools` was not on your path. It could be that you hadn't added it to your $PATH when you got that error (or that you needed to restart your terminal). And `pybedtools` is actually already a dependency of `metaseq`, so it should have been installed when installing metaseq. Anyway, glad it works now!
