### ISSUE TITLE
Bamsignal attributes 

### ISSUE THREAD

**Issue by kellermac** [daler/metaseq#27]
Hi, I am trying to plot some RNA-seq signal in BAM files over an interval. Basically making a heatmap as in example 1only with RNA reads instead of CHiP. I keep getting errors like the following. Looking at the documentation and source code I still can't figure out what attributes a Bamsignal has. How can I make this work? 

    sort_by=s2bulk_signal.mean(axis=1),
AttributeError: 'BamSignal' object has no attribute 'mean'

**Comment by daler** [comment]
In IPython, tab completion is your friend. This will get you all the things BamSignal can do:

```python
s2bulk_signal.<TAB>
```
However, here you're asking about taking the mean across axis 1, which implies that you expect to have an array. All a BamSignal object does is that it describes how to calculate signal from a BAM file. You want to get an array of signal, you need to specify what windows to get the signal over. If you want RNA reads over TSSes, then provide TSSes to the `array()` method and then on the resulting NumPy array you can call `mean(axis=1)`.
